param(
    [string]$OutputDir = ""
)

$ErrorActionPreference = "Stop"

$root = (Resolve-Path -LiteralPath (Join-Path $PSScriptRoot "..")).Path
if ([string]::IsNullOrWhiteSpace($OutputDir)) {
    $stamp = Get-Date -Format "yyyyMMdd-HHmmss"
    $OutputDir = Join-Path "demo-output" ("demo-{0}-{1}" -f $stamp, $PID)
}
$out = if ([IO.Path]::IsPathRooted($OutputDir)) {
    [IO.Path]::GetFullPath($OutputDir)
} else {
    [IO.Path]::GetFullPath((Join-Path $root $OutputDir))
}
$case = Join-Path $out "demo.kdft.sqlite"
$report = Join-Path $out "report.html"

if ((Test-Path -LiteralPath $case) -or (Test-Path -LiteralPath $report)) {
    throw "Refusing to replace existing demo output in $out"
}
if (-not (Test-Path -LiteralPath $out)) {
    New-Item -ItemType Directory -Path $out | Out-Null
}

$env:CARGO_TARGET_DIR = Join-Path $env:TEMP "kdft-v1-cargo-check-target"

cargo run -p kdft-cli -- case create --case $case --name "KDFT Demo Case" --examiner "Demo Examiner" --json
cargo run -p kdft-cli -- bookmark folder-create --case $case --name "Findings" --comment "Demo report-ready findings" --json
cargo run -p kdft-cli -- bookmark create --case $case --folder-id 1 --type highlighted_data --data-type Text --title "First report finding" --comment "Generated by scripts/demo-report.ps1" --json
cargo run -p kdft-cli -- bookmark item-add --case $case --bookmark-id 1 --display-name "Selected bytes" --logical-path "/demo/file.txt" --selection-offset 128 --selection-length 16 --data-preview "keyword hit preview" --json
cargo run -p kdft-cli -- report export --case $case --output $report --json

Write-Output "CASE_PATH=$case"
Write-Output "REPORT_PATH=$report"
